server:
  context-path: /
security:
  basic:
    enabled: false
management:
  context-path: /admin
  security:
    enabled: false

eureka:
  instance:
    instanceId: ${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    statusPageUrlPath: https://${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}/${server.context-path}${management.context-path}/info
    healthCheckUrlPath: ${server.context-path}${management.context-path}/health
    home-page-url: https://${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}/${server.context-path}
    status-page-url: https://${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}/${server.context-path}/${management.context-path}/info
    leaseRenewalIntervalInSeconds: 5
    secure-virtual-host-name: ${VSERVICEHOST:${spring.application.name:${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}}}
    virtual-host-name: ${VSERVICEHOST:${spring.application.name:${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}}}
    hostname: ${VSERVICEHOST:${spring.application.name:${VHOSTNAME:${HOSTNAME:localhost.shinigami.io}}}}
    secure-port-enabled: false
    secure-port: ${VSECUREPORT:${server.port}}
    non-secure-port-enabled: true
    non-secure-port: ${VNONSECUREPORT:${server.port}}
  client:
    region: default
    serviceUrl:
      defaultZone: http://${VEUREKAUSER:config}:${VEUREKAPASS:config}@${VEUREKAHOST:localhost.shinigami.io}:${VEUREKAPORT:8761}/registry/eureka
    enabled: true
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
logging:
  level:
    ROOT: INFO
    org.springframework.web: WARN
spring:
  cloud:
    config:
      discovery:
        enabled: true
  user:
    roles: ACTUATOR

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
      circuitBreaker:
        requestVolumeThreshold: 4
        errorThresholdPercentage: 50
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
          numBuckets: 10
  threadpool:
    default:
      coreSize: 4
      maxQueueSize: 8
      queueSizeRejectionThreshold: 5
